CREATE TABLE star
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(20),
    lastname  VARCHAR(20),
    age       INTEGER NOT NULL
);
 INSERT INTO star (id, firstname, lastname, age) VALUES (DEFAULT, 'Felix', 'the Cat', 10), (DEFAULT, 'Tess', 'the Dog', 15);

 CREATE TABLE movies (starid INTEGER, movieid INTEGER PRIMARY KEY, title VARCHAR(40));
 INSERT INTO movies (starid, movieid, title) VALUES (IDENTITY(), 10, 'Felix in Hollywood');